# Generated by Django 5.0 on 2025-10-14 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diplome', '0003_alter_anneeuniv_datedebut'),
        ('matiere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('M.', 'Monsieur'), ('Mme', 'Madame')], max_length=5)),
                ('datedenaissance', models.DateField(null=True)),
                ('Nmoinsun', models.CharField(max_length=255, null=True)),
                ('iaL2', models.BooleanField(default=False)),
                ('alternant', models.BooleanField(default=False)),
                ('neu', models.BooleanField(default=False)),
                ('tierstemps', models.BooleanField(default=False)),
                ('rse', models.BooleanField(default=False)),
                ('photo', models.ImageField(default='photos/image.jpg', upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Inscriptiondiplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteSem1', models.FloatField(blank=True, default=None, null=True)),
                ('rangSem1', models.IntegerField(null=True)),
                ('noteSem2', models.FloatField(blank=True, default=None, null=True)),
                ('rangSem2', models.IntegerField(null=True)),
                ('noteAnnee', models.FloatField(blank=True, default=None, null=True)),
                ('rangAnnee', models.IntegerField(null=True)),
                ('statutDipl', models.CharField(blank=True, choices=[('ADM', 'Admis'), ('ADJ', 'Admis Jury'), ('AJ', 'Ajourne'), ('Sresul', 'Sansresultat')], default=None, max_length=6, null=True)),
                ('datedecisionDipl', models.DateTimeField(default=None, null=True)),
                ('statutS1', models.CharField(blank=True, choices=[('ADM', 'Admis'), ('ADJ', 'Admis Jury'), ('AJ', 'Ajourne'), ('Sresul', 'Sansresultat')], default=None, max_length=6, null=True)),
                ('datedecisionS1', models.DateTimeField(default=None, null=True)),
                ('statutS2', models.CharField(blank=True, choices=[('ADM', 'Admis'), ('ADJ', 'Admis Jury'), ('AJ', 'Ajourne'), ('Sresul', 'Sansresultat')], default=None, max_length=6, null=True)),
                ('datedecisionS2', models.DateTimeField(default=None, null=True)),
                ('anneeuniv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplome.anneeuniv')),
                ('diplome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptionDip', to='diplome.diplome')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptionDipEtud', to='etudiant.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Inscriptionmat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notecc1', models.FloatField(null=True)),
                ('notecc2', models.FloatField(null=True)),
                ('notecc3', models.FloatField(null=True)),
                ('moyenne', models.FloatField(null=True)),
                ('statut', models.CharField(choices=[('ADM', 'Admis'), ('ADJ', 'Admis Jury'), ('AJ', 'Ajourne'), ('Sresul', 'Sansresultat')], max_length=6, null=True)),
                ('decisionmat', models.DateTimeField(null=True)),
                ('rang', models.IntegerField(null=True)),
                ('anneeuniv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplome.anneeuniv')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', related_query_name='etud', to='etudiant.etudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', related_query_name='mat', to='matiere.matiere')),
            ],
        ),
    ]
