# Generated by Django 5.0 on 2025-10-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='rangalpha',
            field=models.IntegerField(null=True),
        ),
    ]
