# Generated by Django 5.0 on 2025-10-16 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0002_etudiant_rangalpha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='rangalpha',
        ),
    ]
