# Generated by Django 5.0 on 2025-11-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0005_remove_etudiant_rangalpha'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='avispoursuite',
            field=models.CharField(choices=[('TF', 'Avis très favorable'), ('FA', 'Avis favorable'), ('RE', 'Avis réservé'), ('DE', 'Avis défavorable')], max_length=2, null=True),
        ),
    ]
