# Generated by Django 5.0 on 2025-11-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0006_etudiant_avispoursuite'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='erasmus',
            field=models.CharField(choices=[('E', 'Entrant'), ('S', 'Sortant')], max_length=1, null=True),
        ),
    ]
