# Generated by Django 5.0 on 2025-11-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0007_etudiant_erasmus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='avispoursuite',
        ),
        migrations.AddField(
            model_name='inscriptiondiplome',
            name='avispoursuite',
            field=models.CharField(choices=[('TF', 'Avis très favorable'), ('FA', 'Avis favorable'), ('RE', 'Avis réservé'), ('DE', 'Avis défavorable')], max_length=2, null=True),
        ),
    ]
