# Generated by Django 5.0 on 2025-11-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0008_remove_etudiant_avispoursuite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='erasmus',
        ),
        migrations.AddField(
            model_name='inscriptiondiplome',
            name='erasmus',
            field=models.CharField(blank=True, choices=[('E', 'Entrant'), ('S', 'Sortant')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='Nmoinsun',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
