# Generated by Django 5.0 on 2025-11-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0009_remove_etudiant_erasmus_inscriptiondiplome_erasmus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='alternant',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='iaL2',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='neu',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='rse',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='tierstemps',
        ),
        migrations.AddField(
            model_name='inscriptiondiplome',
            name='alternant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscriptiondiplome',
            name='iaL2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscriptiondiplome',
            name='neu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscriptiondiplome',
            name='redoublant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscriptiondiplome',
            name='rse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscriptiondiplome',
            name='tierstemps',
            field=models.BooleanField(default=False),
        ),
    ]
