# Generated by Django 5.0 on 2025-11-11 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0010_remove_etudiant_alternant_remove_etudiant_ial2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscriptionmat',
            name='anneeuniv',
        ),
        migrations.RemoveField(
            model_name='inscriptionmat',
            name='etudiant',
        ),
        migrations.AddField(
            model_name='inscriptionmat',
            name='indiplome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etudiant.inscriptiondiplome'),
        ),
    ]
