# Generated by Django 5.0 on 2025-11-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0011_remove_inscriptionmat_anneeuniv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscriptionmat',
            old_name='indiplome',
            new_name='inscriptiondiplome',
        ),
    ]
