# Generated by Django 5.0 on 2025-12-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0012_rename_indiplome_inscriptionmat_inscriptiondiplome'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionmat',
            name='pointjury',
            field=models.FloatField(null=True),
        ),
    ]
