# Generated by Django 5.0 on 2025-12-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0013_inscriptionmat_pointjury'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='Nmoinsun',
        ),
        migrations.AddField(
            model_name='inscriptiondiplome',
            name='Nmoinsun',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
