# Generated by Django 5.0 on 2026-01-01 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplome', '0004_diplome_matieres'),
        ('etudiant', '0014_remove_etudiant_nmoinsun_inscriptiondiplome_nmoinsun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptiondiplome',
            name='anneeuniv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='diplome.anneeuniv'),
        ),
        migrations.AlterField(
            model_name='inscriptiondiplome',
            name='diplome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='diplome.diplome'),
        ),
        migrations.AlterField(
            model_name='inscriptiondiplome',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='etudiant.etudiant'),
        ),
    ]
