# Generated by Django 5.0 on 2026-01-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0015_alter_inscriptiondiplome_anneeuniv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptiondiplome',
            name='avispoursuite',
            field=models.CharField(blank=True, choices=[('TF', 'Avis très favorable'), ('FA', 'Avis favorable'), ('RE', 'Avis réservé'), ('DE', 'Avis défavorable')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='inscriptiondiplome',
            name='datedecisionDipl',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='inscriptiondiplome',
            name='datedecisionS1',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='inscriptiondiplome',
            name='datedecisionS2',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='inscriptiondiplome',
            name='rangAnnee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscriptionmat',
            name='decisionmat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscriptionmat',
            name='moyenne',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscriptionmat',
            name='notecc1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscriptionmat',
            name='notecc2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscriptionmat',
            name='notecc3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscriptionmat',
            name='pointjury',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscriptionmat',
            name='rang',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscriptionmat',
            name='statut',
            field=models.CharField(blank=True, choices=[('ADM', 'Admis'), ('ADJ', 'Admis Jury'), ('AJ', 'Ajourne'), ('Sresul', 'Sansresultat')], max_length=6, null=True),
        ),
    ]
