# Generated by Django 5.0 on 2025-10-22 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diplome', '0003_alter_anneeuniv_datedebut'),
    ]

    operations = [
        migrations.CreateModel(
            name='jury',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datejury', models.DateTimeField(null=True)),
                ('semestre', models.CharField(max_length=3)),
                ('alternant', models.BooleanField()),
                ('anneeuniv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplome.anneeuniv')),
                ('diplome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplome.diplome')),
            ],
        ),
    ]
