# Generated by Django 5.0 on 2025-10-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jury',
            name='fini',
            field=models.BooleanField(default=False),
        ),
    ]
