# Generated by Django 5.0 on 2025-10-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeapogee', models.CharField(max_length=25, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('semestre', models.CharField(max_length=2)),
                ('coefcc1', models.IntegerField()),
                ('coefcc2', models.IntegerField()),
                ('coefcc3', models.IntegerField()),
            ],
        ),
    ]
