# Generated by Django 5.0 on 2025-12-27 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplome', '0003_alter_anneeuniv_datedebut'),
        ('matiere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nbreinscrit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbrInscrit', models.IntegerField()),
                ('anneeuniv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplome.anneeuniv')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matiere.matiere')),
            ],
        ),
    ]
