# Generated by Django 5.0 on 2025-12-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matiere', '0002_nbreinscrit'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbreinscrit',
            name='alt',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
