# Generated by Django 5.0 on 2025-10-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeapogee', models.CharField(max_length=25, unique=True)),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
    ]
