# Generated by Django 5.0 on 2025-10-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anneeuniv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anneeuniv', models.CharField(max_length=9, unique=True)),
                ('encours', models.BooleanField()),
                ('S2', models.BooleanField(db_default=models.Value(False))),
                ('datedebut', models.DateTimeField()),
            ],
        ),
    ]
