# Generated by Django 5.0 on 2025-10-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplome', '0002_anneeuniv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneeuniv',
            name='datedebut',
            field=models.DateField(null=True),
        ),
    ]
