# Generated by Django 5.0 on 2025-12-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplome', '0003_alter_anneeuniv_datedebut'),
        ('matiere', '0003_nbreinscrit_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplome',
            name='matieres',
            field=models.ManyToManyField(to='matiere.matiere'),
        ),
    ]
